# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "./.Xil/Vivado-42516-ice-x230/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7a35tcpg236-1

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib

    # Skipping read_* RTL commands because this is post-elab optimize flow
    set rt::useElabCache true
    if {$rt::useElabCache == false} {
      rt::read_verilog -include {
    /home/icenowy/git-repos/ice-risc/macros
    /home/icenowy/git-repos/ice-risc
  } {
      /home/icenowy/git-repos/ice-risc/alu.v
      /home/icenowy/git-repos/ice-risc/vivado/clock_divider.v
      /home/icenowy/git-repos/ice-risc/control_rv.v
      /home/icenowy/git-repos/ice-risc/vivado/digital_display_driver.v
      /home/icenowy/git-repos/ice-risc/ice_risc_rv.v
      /home/icenowy/git-repos/ice-risc/instr_decode_rv.v
      /home/icenowy/git-repos/ice-risc/instr_split_rv.v
      /home/icenowy/git-repos/ice-risc/vivado/key_debouncer.v
      /home/icenowy/git-repos/ice-risc/next_pc_rv.v
      /home/icenowy/git-repos/ice-risc/pc.v
      /home/icenowy/git-repos/ice-risc/regfile_32.v
      /home/icenowy/git-repos/ice-risc/sign_extend_12_32.v
      /home/icenowy/git-repos/ice-risc/sign_extend_13_32.v
      /home/icenowy/git-repos/ice-risc/sign_extend_16_32.v
      /home/icenowy/git-repos/ice-risc/sign_extend_21_32.v
      /home/icenowy/git-repos/ice-risc/sign_extend_8_32.v
      /home/icenowy/git-repos/ice-risc/simple_memory.v
      /home/icenowy/git-repos/ice-risc/sub_word_d_mem_read_rv.v
      /home/icenowy/git-repos/ice-risc/vivado/top.v
    }
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification true
    set rt::SDCFileList ./.Xil/Vivado-42516-ice-x230/realtime/top_synth.xdc
    rt::sdcChecksum
    set rt::top top
    rt::set_parameter enableIncremental true
    set rt::reportTiming false
    rt::set_parameter elaborateOnly false
    rt::set_parameter elaborateRtl false
    rt::set_parameter eliminateRedundantBitOperator true
    rt::set_parameter elaborateRtlOnlyFlow false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter ramStyle auto
    rt::set_parameter merge_flipflops true
# MODE: 
    rt::set_parameter webTalkPath {/home/icenowy/git-repos/ice-risc/vivado/ice-risc.cache/wt}
    rt::set_parameter enableSplitFlowPath "./.Xil/Vivado-42516-ice-x230/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_synthesis -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    rt::HARTNDb_reportJobStats "Synthesis Optimization Runtime"
    rt::HARTNDb_stopSystemStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
