/************************************************************\
 **  Copyright (c) 2011-2021 Anlogic, Inc.
 **  All Right Reserved.
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	/home/icenowy/git-repos/ice-risc/al_ip/dram.v
 ** Date	:	2018 12 05
 ** TD version	:	4.2.217
\************************************************************/

`timescale 1ns / 1ps

module dram ( di, waddr, we, wclk, do, raddr );

	parameter DATA_WIDTH_W = 32; 
	parameter ADDR_WIDTH_W = 6;
	parameter DATA_DEPTH_W = 44;
	parameter DATA_WIDTH_R = 32;
	parameter ADDR_WIDTH_R = 6;
	parameter DATA_DEPTH_R = 44;

	input  [DATA_WIDTH_W-1:0] di;
	input  [ADDR_WIDTH_W-1:0] waddr;
	input  [ADDR_WIDTH_R-1:0] raddr;
	input  wclk,we;

	output [DATA_WIDTH_R-1:0] do;



	EG_LOGIC_DRAM #(
 			.INIT_FILE("../rom.mif"),
			.DATA_WIDTH_W(DATA_WIDTH_W),
			.ADDR_WIDTH_W(ADDR_WIDTH_W),
			.DATA_DEPTH_W(DATA_DEPTH_W),
			.DATA_WIDTH_R(DATA_WIDTH_R),
			.ADDR_WIDTH_R(ADDR_WIDTH_R),
			.DATA_DEPTH_R(DATA_DEPTH_R))
		dram(
			.di(di),
			.waddr(waddr),
			.wclk(wclk),
			.we(we),
			.do(do),
			.raddr(raddr));

endmodule