# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/icenowy/git-repos/ice-risc/vivado/ice-risc.cache/wt [current_project]
set_property parent.project_path /home/icenowy/git-repos/ice-risc/vivado/ice-risc.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/icenowy/git-repos/ice-risc/vivado/ice-risc.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog {
  /home/icenowy/git-repos/ice-risc/macros/aluops.v
  /home/icenowy/git-repos/ice-risc/macros/control_rv.v
  /home/icenowy/git-repos/ice-risc/macros/control.v
  /home/icenowy/git-repos/ice-risc/macros/functions_rv.v
  /home/icenowy/git-repos/ice-risc/macros/opcodes_rv.v
  /home/icenowy/git-repos/ice-risc/simple_memory_rom.v
}
set_property file_type "Verilog Header" [get_files /home/icenowy/git-repos/ice-risc/macros/aluops.v]
set_property file_type "Verilog Header" [get_files /home/icenowy/git-repos/ice-risc/macros/control_rv.v]
set_property file_type "Verilog Header" [get_files /home/icenowy/git-repos/ice-risc/macros/control.v]
set_property file_type "Verilog Header" [get_files /home/icenowy/git-repos/ice-risc/macros/functions_rv.v]
set_property file_type "Verilog Header" [get_files /home/icenowy/git-repos/ice-risc/macros/opcodes_rv.v]
set_property file_type "Verilog Header" [get_files /home/icenowy/git-repos/ice-risc/simple_memory_rom.v]
read_verilog -library xil_defaultlib {
  /home/icenowy/git-repos/ice-risc/alu.v
  /home/icenowy/git-repos/ice-risc/vivado/clock_divider.v
  /home/icenowy/git-repos/ice-risc/control_rv.v
  /home/icenowy/git-repos/ice-risc/vivado/digital_display_driver.v
  /home/icenowy/git-repos/ice-risc/ice_risc_rv.v
  /home/icenowy/git-repos/ice-risc/instr_decode_rv.v
  /home/icenowy/git-repos/ice-risc/instr_split_rv.v
  /home/icenowy/git-repos/ice-risc/vivado/key_debouncer.v
  /home/icenowy/git-repos/ice-risc/next_pc_rv.v
  /home/icenowy/git-repos/ice-risc/pc.v
  /home/icenowy/git-repos/ice-risc/regfile_32.v
  /home/icenowy/git-repos/ice-risc/sign_extend_12_32.v
  /home/icenowy/git-repos/ice-risc/sign_extend_13_32.v
  /home/icenowy/git-repos/ice-risc/sign_extend_16_32.v
  /home/icenowy/git-repos/ice-risc/sign_extend_21_32.v
  /home/icenowy/git-repos/ice-risc/sign_extend_8_32.v
  /home/icenowy/git-repos/ice-risc/simple_memory.v
  /home/icenowy/git-repos/ice-risc/sub_word_d_mem_read_rv.v
  /home/icenowy/git-repos/ice-risc/vivado/top.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/icenowy/git-repos/ice-risc/vivado/clocks.xdc
set_property used_in_implementation false [get_files /home/icenowy/git-repos/ice-risc/vivado/clocks.xdc]

read_xdc /home/icenowy/git-repos/ice-risc/vivado/pins.xdc
set_property used_in_implementation false [get_files /home/icenowy/git-repos/ice-risc/vivado/pins.xdc]

read_xdc /home/icenowy/git-repos/ice-risc/vivado/ice-risc.srcs/constrs_1/new/configuration.xdc
set_property used_in_implementation false [get_files /home/icenowy/git-repos/ice-risc/vivado/ice-risc.srcs/constrs_1/new/configuration.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top top -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
