`define ALU_OP_ADD	6'd0
`define ALU_OP_SLT	6'd1
`define ALU_OP_SLTU	6'd2
`define ALU_OP_AND	6'd3
`define ALU_OP_OR	6'd4
`define ALU_OP_XOR	6'd5
`define ALU_OP_SLL	6'd6
`define ALU_OP_SRL	6'd7
`define ALU_OP_SUB	6'd8
`define ALU_OP_SRA	6'd9
`define ALU_OP_EQ	6'd10
