`define ALU_OP_ADD	4'd0
`define ALU_OP_SLT	4'd1
`define ALU_OP_SLTU	4'd2
`define ALU_OP_AND	4'd3
`define ALU_OP_OR	4'd4
`define ALU_OP_XOR	4'd5
`define ALU_OP_SLL	4'd6
`define ALU_OP_SRL	4'd7
`define ALU_OP_SUB	4'd8
`define ALU_OP_SRA	4'd9
`define ALU_OP_EQ	4'd10
